version: '3.3'
services:
    db:
        container_name: contain_mysql
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD : password
        networks:
            - my-network
        volumes:
            - ./db/:/var/lib/mysql/
        ports:
          - 8082:3306
    wordpress:
        container_name: contain_wordpress
        image: 'wordpress:5.8.1-apache'
        ports:
            - 8080:80
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: password
          WORDPRESS_DB_NAME: db
        volumes:
          - ./wordpress/:/var/www/html/
        links:
          - db
        networks:
          - my-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8081:80
        environment:
          - PMA_ARBITRARY=1
        links:
          - db
        networks:
          - my-network
networks:
  my-network:
    driver: bridge


